CREATE DATABASE SOMU
USE SOMU
CREATE TABLE T1(
ID INT,
NAME VARCHAR(5),
AGE INT)
SELECT * FROM T1
SELECT ID FROM T1
INSERT INTO T1 VALUES(3,'AJAY',26),(4,'ARIF',22),(5,'HARIS',25)
SELECT DISTINCT * FROM T1
 
